version: "3.8"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb"
    image: "amazon/dynamodb-local:3.1.0"
    ports:
      - "8000:8000"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    tty: true
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
