# lint_and_test.yml
name: Lint and Test

on:
  push:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    services:
      dynamodb:
        image: amazon/dynamodb-local:2.6.0
        ports:
          - 8000:8000
        options: --name dynamodb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run flake8 linter
        run: |
          poetry run flake8 .

      - name: Run unittest
        run: |
          poetry run pytest --cov=ddb_single -v

      - name: Test Build
        run: |
          poetry build

      - name: Generate docs
        run: |
          cp ./readme.md ./docs_src/readme.md
          poetry run sphinx-apidoc -f -o ./docs_src ./ddb_single
          poetry run sphinx-build ./docs_src ./docs

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: lint_and_test
    permissions:
      contents: write
      id-token: write
      pages: write
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
