name: Release
on:
  workflow_dispatch:
    inputs:
      rule:
        description: "Rule to run"
        required: false
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install poetry

      - name: Get Version
        run: |
          version=$(poetry version -s)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git fetch --prune --unshallow
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Get changelog
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tag_prefix: ''
          release_branches: master
          dry_run: true

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Publish package
        env:
          PYPI_LOCAL_USERNAME: __token__
          PYPI_LOCAL_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry build
          poetry publish -u $PYPI_LOCAL_USERNAME -p $PYPI_LOCAL_PASSWORD
